var nameList = [
  'Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Krishna', 'Rohan',
  'Rahul', 'Karthik', 'Anirudh', 'Siddharth', 'Harsha', 'Manoj', 'Varun',
  'Abhinav', 'Gautam', 'Nikhil', 'Pranav', 'Shiva',

  'Ananya', 'Aditi', 'Diya', 'Saanvi', 'Isha', 'Kavya', 'Riya', 'Pooja',
  'Meera', 'Sneha', 'Swathi', 'Lakshmi', 'Divya', 'Shreya', 'Harini',
  'Priya', 'Neha', 'Soumya', 'Bhavya', 'Radha',

  'Teja', 'Charan', 'Vamsi', 'Surya', 'Mounika', 'Chaitanya', 'Ramya',
  'Sravani', 'Rajesh', 'Madhavi', 'Sandeep', 'Lalitha', 'Rakesh',
  'Anusha', 'Deepak', 'Sunitha', 'Suhas', 'Kiran', 'Padma', 'Raghu'
];

export function generate() { return  nameList[Math.floor(Math.random() * nameList.length)]; }

var commentList = [
  "First like 🔥🔥",
  "Who's still watching in 2025?",
  "This song never gets old ❤️",
  "Bro dropped this and vanished 💀",
  "Nostalgia hitting hard rn 😭",
  "Anyone from India here? 🇮🇳",
  "This deserves more views!",
  "I came here after seeing the meme 😂",
  "Why is no one talking about the beat??",
  "Respect for the editor 👏",
  "The lyrics >>>>",
  "Childhood memories unlocked 😭",
  "Who else listening at 2 AM?",
  "This song hits different with headphones 🎧",
  "OG fans where you at?",
  "Only legends remember this!",
  "This video is pure masterpiece 🔥",
  "Man, YouTube recommendations still fire sometimes",
  "No autotune, just pure talent 🙌",
  "This is underrated fr!",
  "10 years later, still iconic.",
  "Who's here after reels ruined this song? 🤦‍♂️",
  "The comment section never disappoints 😂",
  "Bro gave us free therapy with this.",
  "The nostalgia is REAL!",
  "That one dislike is from my ex 😤",
  "Imagine hearing this live 😳",
  "This should be illegal to skip 🔥",
  "Back when YouTube was golden ✨",
  "This will forever be in my playlist.",
  "Not me crying at 3 AM 😭",
  "This comment section is like a reunion 😂",
  "Real ones never left this song!",
  "The beat drop >>> whole industry",
  "This is giving me goosebumps 😳",
  "This deserves a billion views!",
  "2025 and still no one can top this.",
  "Legends never die 🔥",
  "My childhood in one video 😭",
  "Bro made history with this.",
  "Respect for the artist 🙌",
  "Can’t believe this is 10+ years old!",
  "Still sounds fresh today 🔥",
  "POV: you’re scrolling while listening 🎧",
  "I showed this to my dad, he’s now a fan 😂",
  "This song raised me 💯",
  "People who disliked this need help 💀",
  "Forever a classic 👑",
  "Best collab ever!",
  "This unlocked hidden memories 😭",
  "Not a song, it’s a feeling ❤️",
  "Came here after so long… chills again!",
  "The music hits your soul 🥺",
  "One of the best uploads ever 🔥",
  "Who else has this on loop?",
  "Man, YouTube comments always vibe 😂",
  "Imagine never hearing this masterpiece 💔",
  "This aged like fine wine 🍷",
  "Legends still listening rn 👇",
  "Pure talent, no auto-tune 🙌",
  "Recommended after 7 years 👀",
  "This is too good for this generation 😂",
  "I remember dancing to this as a kid!",
  "Stream this till it hits 1B 🔥",
  "Real music >>>",
  "The nostalgia is unmatched 😭",
  "Only true fans know every lyric!",
  "YouTube recommendations never miss 👌",
  "This deserves an award 🏆",
  "This song was way ahead of its time.",
  "This brings back my school memories 🥺",
  "Instant goosebumps every time.",
  "Masterpiece, nothing less ❤️",
  "Still better than 90% of today’s music.",
  "Can't believe this is free on YouTube 💯",
  "Every second of this is gold ✨",
  "This hits harder the older you get 😭",
  "Anyone else vibing alone rn? 🙋‍♂️",
  "So underrated, it hurts 💔",
  "This video is pure art 🎨",
  "Who came from TikTok trend? 😂",
  "Absolute legend dropped this 🔥",
  "The comments are half the fun 😂",
  "10/10 no skips.",
  "Forever iconic 🕊️",
  "Every time I hear this, I feel alive.",
  "This will never get old.",
  "2025 gang where you at?",
  "The OGs know what’s up!",
  "This needs to be in every playlist.",
  "Shoutout to YouTube recommendations 🙏",
  "Not a song, this is therapy ❤️",
  "This is why I love music.",
  "This video is literally timeless.",
  "The chorus lives rent-free in my head 😂",
  "This is straight fire 🔥🔥🔥",
  "Every time this plays, my mood lifts.",
  "Old is gold 💯",
  "Legends listening in silence rn…",
  "One of the best to ever exist.",
  "I showed this to my mom, she cried 😭",
  "Pure nostalgia bomb 💣",
  "Only legends still here in 2025!",
  "Music like this never dies.",
  "Bro carried an entire generation 💯",
  "This is a masterpiece, hands down.",
  "Feels like I’m back in 2010!",
  "Chills every single time 🥶",
  "The dislikes are from bots 💀",
  "One word: Legendary.",
  "This will always be iconic.",
  "Every lyric hits different.",
  "This should have 1B+ views already.",
  "Can’t skip even for a sec 🔥",
  "Who else has goosebumps rn?",
  "They don’t make music like this anymore 💔",
  "The flow is unmatched.",
  "This defines perfection 🙌",
  "The nostalgia is too real!",
  "Everyone here has good taste 👏",
  "Pure vibes only 💯",
  "Still one of the best to exist.",
  "YouTube at its peak ✨",
  "This should be in a museum 😂",
  "Certified classic.",
  "Even after 15 years… still 🔥",
  "This is the definition of timeless.",
  "Legends still vibing rn 👀",
  "Bro made history here.",
  "I’ll never get tired of this song.",
  "2025 listeners unite!",
  "This beat slaps harder than life 😂",
  "Back when music was REAL.",
  "Forever in my heart ❤️",
  "I’m literally crying rn 😭",
  "Absolute banger!",
  "This unlocked childhood vibes.",
  "Who else watching with headphones on? 🎧",
  "Every second = goosebumps.",
  "Legends pressing replay rn 🔁",
  "Real talent, no gimmicks.",
  "The comments are better than therapy 😂",
  "Still fire after all these years 🔥",
  "This is my childhood in a nutshell.",
  "Can’t explain how much I love this.",
  "Pure masterpiece energy ✨",
  "This deserves more recognition.",
  "Even my kids will vibe to this 😂",
  "The melody >>>",
  "Still iconic after all these years.",
  "This will never fade away.",
  "Legends were made here.",
  "Who’s here after school homework vibes? 📚",
  "I can’t stop smiling rn 😭",
  "Classic forever.",
  "The talent is unreal.",
  "Respect to the artist forever 🙏",
  "The real ones never left 💯",
  "Every generation deserves this song.",
  "This is why I love YouTube ❤️",
  "Masterpiece. Period.",
  "The vibes are unmatched.",
  "Timeless and flawless.",
  "Still slaps harder than anything rn.",
  "Legends still pressing play.",
  "Music like this heals ❤️",
  "This hits harder than expected.",
  "Pure nostalgia therapy 🥺",
  "Even better today than back then.",
  "Forever grateful for this song 🙌",
  "Chills every replay.",
  "2025 gang dropping likes 👍",
  "This comment section is legendary.",
  "Bro made an anthem 🔥",
  "This never disappoints.",
  "Still a masterpiece 💯",
  "Everyone’s childhood right here.",
  "The vibes are immaculate ✨",
  "This never gets old ❤️"
];

export function generateComment() { return  commentList[Math.floor(Math.random() * commentList.length)]; }
